apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service-v2
  labels:
    app: recommendation-service
    version: v2
spec:
  replicas: 1

  selector:
    matchLabels:
      app: recommendation-service
      version: v2

  template:
    metadata:
      labels:
        app: recommendation-service
        version: v2

    spec:
      containers:
        - name: recommendation-service
          image: recommendation-service:v2
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: SERVICE_VERSION
              value: "v2"

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
